-- Generated by `go test ./internal/store/sqlite/... -update`. Do not edit by hand.

CREATE TABLE users (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,

    -- NOCASE so that the address is one identity however it was typed. The
    -- unique index below inherits the collation, which is what stops
    -- "Alice@example.com" from becoming a second account.
    email         TEXT NOT NULL COLLATE NOCASE,

    -- The bcrypt digest, as produced by internal/auth.
    password_hash TEXT NOT NULL,

    -- Stored as issued rather than hashed; the reason is on model.User.APIKey.
    api_key       TEXT NOT NULL,

    -- Unix seconds, UTC. Times are integers throughout the schema because
    -- points.timestamp arrives from the API as a Unix timestamp and is compared
    -- by range on every request; storing some times as text would mean a
    -- conversion in those comparisons, and two ways to be wrong.
    created_at    INTEGER NOT NULL,
    updated_at    INTEGER NOT NULL
) STRICT;

CREATE UNIQUE INDEX users_email_key ON users (email);

CREATE UNIQUE INDEX users_api_key_key ON users (api_key);

CREATE TABLE points (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id           INTEGER NOT NULL REFERENCES users (id),

    -- Unix seconds, UTC, for the reason on users.created_at.
    timestamp         INTEGER NOT NULL,

    latitude          REAL NOT NULL,
    longitude         REAL NOT NULL,

    -- Everything below is a device property that may or may not have been
    -- sent, so NULL is a real value here: it means "not reported", not zero.
    altitude          REAL,
    velocity          REAL,
    accuracy          REAL,
    vertical_accuracy REAL,
    course            REAL,
    course_accuracy   REAL,
    battery_status    TEXT,
    battery           REAL,
    ssid              TEXT,
    tracker_id        TEXT,

    created_at        INTEGER NOT NULL,
    updated_at        INTEGER NOT NULL
) STRICT;

CREATE UNIQUE INDEX points_user_id_timestamp_key ON points (user_id, timestamp);

CREATE TABLE daily_stats (
    user_id                 INTEGER NOT NULL REFERENCES users (id),

    -- Local midnight of the day this row covers, formatted "YYYY-MM-DD" in
    -- whatever timezone TRAVELMAP_TIMEZONE named when the row was built.
    day                     TEXT NOT NULL,

    points                  INTEGER NOT NULL,
    reverse_geocoded_points INTEGER NOT NULL,
    km                      REAL NOT NULL,

    -- JSON arrays of the country and city names visited that day. Empty
    -- ("[]") until reverse geocoding (Milestone G) is enabled.
    countries               TEXT NOT NULL,
    cities                  TEXT NOT NULL,

    PRIMARY KEY (user_id, day)
) STRICT;
