package sqlite

import (
	"flag"
	"os"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/pressly/goose/v3"
)

// schemaPath is where the schema snapshot lives, beside the migrations that
// build it up.
const schemaPath = "schema.sql"

// schemaHeader marks the file as generated, the way every other checked-in
// generated file in this module does.
const schemaHeader = `-- Generated by ` + "`go test ./internal/store/sqlite/... -update`" + `. Do not edit by hand.

`

// update rewrites the schema snapshot instead of comparing against it:
// `go test ./internal/store/sqlite/... -update`.
var update = flag.Bool("update", false, "update the schema snapshot")

// TestSchema pins the schema a fresh checkout ends up with once every
// migration has run, in schema.sql. The migrations only ever show a diff from
// the version before them; this is the file that shows the structure they add
// up to without replaying them by hand — the Go equivalent of Rails'
// db/schema.rb.
//
// Regenerate with `go test ./internal/store/sqlite/... -update` whenever a
// migration changes the schema; a stale file fails this test, which `make
// test` and the pre-commit hook both already run, so nothing further has to
// remember to catch it.
func TestSchema(t *testing.T) {
	t.Parallel()

	db := newTestDB(t)

	// sqlite_master lists every object in creation order by rowid, which is
	// also migration order — closer to reading the migrations concatenated
	// than an alphabetical listing would be. goose's own bookkeeping table
	// and SQLite's internal ones are not part of this schema.
	rows, err := db.q.QueryContext(t.Context(),
		`SELECT sql FROM sqlite_master
		 WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' AND name != ?
		 ORDER BY rowid`,
		goose.DefaultTablename,
	)
	if err != nil {
		t.Fatalf("querying sqlite_master returned %v", err)
	}
	defer rows.Close()

	var statements []string

	for rows.Next() {
		var stmt string
		if err := rows.Scan(&stmt); err != nil {
			t.Fatalf("scanning sqlite_master returned %v", err)
		}

		statements = append(statements, stmt+";")
	}

	if err := rows.Err(); err != nil {
		t.Fatalf("reading sqlite_master returned %v", err)
	}

	want := schemaHeader + strings.Join(statements, "\n\n") + "\n"

	if *update {
		if err := os.WriteFile(schemaPath, []byte(want), 0o600); err != nil {
			t.Fatalf("writing %s: %v", schemaPath, err)
		}

		return
	}

	got, err := os.ReadFile(schemaPath)
	if err != nil {
		t.Fatalf("reading %s (run `go test ./internal/store/sqlite/... -update` to create it): %v", schemaPath, err)
	}

	if diff := cmp.Diff(want, string(got)); diff != "" {
		t.Errorf("%s is stale (-want +got); regenerate with `go test ./internal/store/sqlite/... -update`:\n%s", schemaPath, diff)
	}
}
