-- Generated by `go test ./internal/store/sqlite/... -update`. Do not edit by hand.

CREATE TABLE users (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,

    -- NOCASE so that the address is one identity however it was typed. The
    -- unique index below inherits the collation, which is what stops
    -- "Alice@example.com" from becoming a second account.
    email         TEXT NOT NULL COLLATE NOCASE,

    -- The bcrypt digest, as produced by internal/auth.
    password_hash TEXT NOT NULL,

    -- Stored as issued rather than hashed; the reason is on model.User.APIKey.
    api_key       TEXT NOT NULL,

    -- Unix seconds, UTC. Times are integers throughout the schema because
    -- points.timestamp arrives from the API as a Unix timestamp and is compared
    -- by range on every request; storing some times as text would mean a
    -- conversion in those comparisons, and two ways to be wrong.
    created_at    INTEGER NOT NULL,
    updated_at    INTEGER NOT NULL
) STRICT;

CREATE UNIQUE INDEX users_email_key ON users (email);

CREATE UNIQUE INDEX users_api_key_key ON users (api_key);

CREATE TABLE points (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id           INTEGER NOT NULL REFERENCES users (id),

    -- Unix seconds, UTC, for the reason on users.created_at.
    timestamp         INTEGER NOT NULL,

    latitude          REAL NOT NULL,
    longitude         REAL NOT NULL,

    -- Everything below is a device property that may or may not have been
    -- sent, so NULL is a real value here: it means "not reported", not zero.
    altitude          REAL,
    velocity          REAL,
    accuracy          REAL,
    vertical_accuracy REAL,
    course            REAL,
    course_accuracy   REAL,
    battery_status    TEXT,
    battery           REAL,
    ssid              TEXT,
    tracker_id        TEXT,

    created_at        INTEGER NOT NULL,
    updated_at        INTEGER NOT NULL
) STRICT;

CREATE TABLE daily_stats (
    user_id                 INTEGER NOT NULL REFERENCES users (id),

    -- Local midnight of the day this row covers, formatted "YYYY-MM-DD" in
    -- whatever timezone TRAVELMAP_TIMEZONE named when the row was built.
    day                     TEXT NOT NULL,

    points                  INTEGER NOT NULL,
    reverse_geocoded_points INTEGER NOT NULL,
    km                      REAL NOT NULL,

    -- JSON arrays of the country and city names visited that day. Empty
    -- ("[]") until reverse geocoding (Milestone G) is enabled.
    countries               TEXT NOT NULL,
    cities                  TEXT NOT NULL,

    PRIMARY KEY (user_id, day)
) STRICT;

CREATE UNIQUE INDEX points_user_id_timestamp_key ON points (
    -- Deduplicates inserts on conflict; also serves GET /points' time filter.
    user_id, timestamp
);

CREATE TABLE checkins (
    id                    INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id               INTEGER NOT NULL REFERENCES users (id),

    -- 24 hex characters, the payload's checkin.id.
    foursquare_checkin_id TEXT NOT NULL,

    -- The check-in's own time (checkin.createdAt), not created_at below.
    checked_in_at         INTEGER NOT NULL,

    -- Minutes, checkin.timeZoneOffset; nullable like every column through shout, since the documented payload is narrower than what has been observed to arrive.
    timezone_offset       INTEGER,

    -- Nullable, like every venue-derived column below, for a check-in without a venue — a shape that has not itself been observed.
    venue_id              TEXT,
    venue_name            TEXT,
    latitude              REAL,
    longitude             REAL,

    -- The payload's cc: stable, unlike the localised text below.
    country_code          TEXT,

    city                  TEXT,
    state                 TEXT,
    country               TEXT,
    category_id           TEXT,
    category_name         TEXT,

    -- Absent as a key, not empty, in the observed push.
    shout                 TEXT,

    -- 'push' or 'sync'; a repeat write keeps this and created_at, refreshes everything else.
    source                TEXT NOT NULL,

    -- The check-in JSON as received; not this server's to re-request at will.
    raw                   TEXT NOT NULL,

    created_at            INTEGER NOT NULL,
    updated_at            INTEGER NOT NULL
) STRICT;

CREATE UNIQUE INDEX checkins_foursquare_checkin_id_key ON checkins (foursquare_checkin_id);

CREATE INDEX checkins_user_id_checked_in_at_idx ON checkins (
    -- Mirrors points(user_id, timestamp): narrows by user and time range first.
    user_id, checked_in_at
);

CREATE TABLE foursquare_accounts (
    -- One Swarm account per travelmap user.
    user_id            INTEGER PRIMARY KEY REFERENCES users (id),

    -- TEXT: the payload sends it quoted ("1709193"). Its unique index resolves a push to one user.
    foursquare_user_id TEXT NOT NULL,

    -- Stored as issued, per "Third-party credentials" in TODO.md's Technical Decisions.
    access_token       TEXT NOT NULL,

    -- The end of the last successful fetch window; NULL until the first one succeeds.
    synced_through     INTEGER,

    created_at         INTEGER NOT NULL,
    updated_at         INTEGER NOT NULL
) STRICT;

CREATE UNIQUE INDEX foursquare_accounts_foursquare_user_id_key ON foursquare_accounts (foursquare_user_id);
